name: Build and Push Docker Image
on:
  push:
    branches:
      - main

env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Login to DockerHub
      run: docker login -u $USERNAME -p $DOCKER_TOKEN
      
    - name: Build and push Docker image
      run: |
        docker build -t yassinedha/devopsgithubactions:latest .
        docker push yassinedha/devopsgithubactions:latest
